# Generated by Django 3.2.2 on 2021-05-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commentonblog',
            name='Blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog_name', to='blog.blog'),
        ),
    ]
