# Generated by Django 3.2.2 on 2021-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_commentonblog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonblog',
            name='comments',
            field=models.TextField(),
        ),
    ]
