# Generated by Django 3.2.2 on 2021-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentonblog_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonblog',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
