# Generated by Django 3.2.2 on 2021-05-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_commentonblog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content_para2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_content_para3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentonblog',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
