# Generated by Django 3.2.2 on 2021-05-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_commentonblog_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentonblog',
            name='Blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
