# Generated by Django 3.2.2 on 2021-05-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_commentonblog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentonblog',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commentonblog',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
