# Generated by Django 3.2.2 on 2021-05-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='to_date',
        ),
        migrations.AddField(
            model_name='workshop',
            name='date_and_time',
            field=models.CharField(default='12/05/2021', max_length=254),
            preserve_default=False,
        ),
    ]
