# Generated by Django 3.2.2 on 2021-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20210514_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=6),
            preserve_default=False,
        ),
    ]
